version: '3'

services: 
  websphere-traditional-customized:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9043:9043
      - 9443:9443
    environment:
      ENABLE_BASIC_LOGGING: 'true'
